### ISSUE TITLE
yeşil bomba tam yeşil değil.

### ISSUE THREAD

**Issue by acarist** [ardiye/tutorial-HideTheBomb#1]
yeşil bomba tam yeşil değil. kırmızı bombanın hex kodu yanlış. bu yüzden sana puanım 1

**Comment by yusucan** [comment]
+1

**Comment by refo** [comment]
Tamam, anladık, komiksiniz. Dağılın şimdi, sonra sabah uyanamıyorsunuz.

**Comment by refo** [comment]
Bombalar gizlendiğinde renkleri gözükmediğinden bu issue'yu kapatıyorum.
